### ISSUE TITLE
Release 1.923

### ISSUE THREAD

**Issue by stuartmp** [QuantAsylum/QA401#15]
Hi Matt  / @QuantAsylum,

Thanks for addressing these issues. I ran some tests this morning and noticed.
1.  AmpTdhVersusInoutLevel does work up to 96K but you need to enter in 95999.0 This may confuse some users trying to use 96K. (see attached photo) If you run it at 96K it does work for THD but for THD+N it doesn't work unless you use 95999.0 Also when I exported the trace using 96K as a CSV file I got 'Freq, NaN' for the results. I traces exported just fine when I used 95999.0

![20210207_093450](https://user-images.githubusercontent.com/4042250/107133572-567abe80-6935-11eb-8dc8-54d8eb5952b3.jpg)

2.  AmpThdVersusFreq doesn't seam to accept any values above 20K just as it was before. When I did run a plot at up to 20K it seamed to cut off a 6.5K (see attached images)

![20210207_110357](https://user-images.githubusercontent.com/4042250/107133564-524ea100-6935-11eb-9f80-244de0cb51b4.jpg)
![20210207_110531](https://user-images.githubusercontent.com/4042250/107133568-55499180-6935-11eb-9dc4-737272ee42c3.jpg)

Can you please look into this and provide some feedback.

_Originally posted by @stuartmp in https://github.com/QuantAsylum/QA401/issues/6#issuecomment-774570990_

**Comment by stuartmp** [comment]
Hi @QuantAsylum any news on this issue.

**Comment by QuantAsylum** [comment]
Hi @stuartmp 

Try again on 1.924 and let me know what you see. Remember when you first asked for this I said there were deep issues that would make this very suboptimal. We can revisit for the 2.0 late in the summer as the new 2.0 SW will make cleanup on these issues pretty easy.

**Comment by stuartmp** [comment]
Hi Matt,

Seams to be working just fine now.
Thank you for fixing that. It's now for me anyway just what I need. I would like to see a right only check box as that's the channel that produces the lowest internal noise for me so I don't use the left one and its a pain to have to remove it from the plot all the time.

It would also be nice to see the filename of the picture export default to the title if possible.

What's the story with the plot residual . How do we use that and can we have that on the right channel please.

Keep up the awesome work. I'm looking forward to V2.0

P.s. you should check out this thread.
I've posted heaps of images of the QA401 results lately.

https://www.diyaudio.com/forums/showthread.php?t=192431

diyAB Amp - The "Honey Badger"

Kind regards

Stuart 



On 27 March 2021 2:07:54 am AEST, QuantAsylum ***@***.***> wrote:
>Hi @stuartmp 
>
>Try again on 1.924 and let me know what you see. Remember when you
>first asked for this I said there were deep issues that would make this
>very suboptimal. We can revisit for the 2.0 late in the summer as the
>new 2.0 SW will make cleanup on these issues pretty easy. 
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/QuantAsylum/QA401/issues/15#issuecomment-808336836

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
