### ISSUE TITLE
QA410 icon not displaying correctly

### ISSUE THREAD

**Issue by pmfawcett** [QuantAsylum/QA401#5]
Matt,

Back to the QA401 after some time away.  Ever since early versions,  the software has never displayed anything but a generic "blank page" icon (see desktop and taskbar shortcuts in attached image).  It's just an annoyance, and I had assumed you had never provided one unique to your product -- but when doing an install on a new laptop today I decided to change it to something more distinguishable... and discovered there may just be an issue with the path... looks like its hard-coded for your personal machine?

Cheers, 

Paul
<img width="960" alt="QA_icon" src="https://user-images.githubusercontent.com/28827526/93231917-488a8e00-f747-11ea-8fc6-c7f2085b6422.png">

**Comment by QuantAsylum** [comment]
Noted, thanks. There was a previous issue with icons not showing up in the task bar that seemed to have been resolved after the icon cache was flushed, but indeed you've spotted an issue. That is a very old link, from the first versions of the app (Visual Studio 2010?!). Thanks very much for reporting

**Comment by QuantAsylum** [comment]
This is fixed in 1.918
