### ISSUE TITLE
Extend plug-ins to work with 192K settings

### ISSUE THREAD

**Issue by QuantAsylum** [QuantAsylum/QA401#6]
Currently, the plugins all assume a 48K sample rate, and there are limitations applied to ensure choices can't be made that would result in an error if the sample rate and the user-entered options aren't consistent (eg , 48K sample rate but user wants to measure THD up to 50 kHz). 

Ideally, the each plug-in could query the sample rate and adjust accordingly.

**Comment by stuartmp** [comment]
It would be great if the sample rate was read / queried from the setting and tge parameters for the plugin adjusted accordingly.

I would also be very much appreciated if the minimum dB increment could be lowered from 1 to 0.1

@QuantAsylum "measure THD up to 50 kHz"

Just confirming that I would like to measure THD up to 96Khz (slightly less so the fft packet size is right) using a generator setting from say 20hz to at least 15.999khz so the THD and THD+N can be calculated on at least 6 harmonics.

**Comment by stuartmp** [comment]
Hi @QuantAsylum , is there any timeline on this issue?

**Comment by QuantAsylum** [comment]
This is a sizable change, and the current internal and external interfaces are going away and getting replaced with REST in 2.0 (see QA401H for direction). So, it probably won't happen until the 2.0 release, which if I had to guess would be later 1Q of next year. The root issue is that all the UI for the plugins is generated at run time, and there's no way to tell the generated controls to check the main app and learn the sample rate and then display accordingly.

**Comment by stuartmp** [comment]
Thanks for that @QuantAsylum in the mean time, would it be possible to just hard code a version of the QA401 software with the sample rate set to 192k

**Comment by QuantAsylum** [comment]
Hi Stuart, unfortunately that gets messy and a lot of extra work to have different flavors of the app. Are bugfixes in the mainline version to be propagated to the special build? For how long? What about corner cases found in the special app? Fix those? Live with them? Where to release the special app? etc. 

Have you looked at IMD? That's generally the way higher freq non-linearities are determined for class D at 20 kHz since they have so much rolloff after 20 kHz. It's pretty definitive.

**Comment by QuantAsylum** [comment]
AmpThdVersusFreq and AmpTdhVersusInoutLevel have had the limits extended in release [1.923](https://github.com/QuantAsylum/QA401/releases/tag/1.923). Beyond that, this will be addressed generically in the 2.0 release for the QA402 in March, with the QA401 support to release 2.0 probably being added mid- to late summer 2021.

**Comment by stuartmp** [comment]
Hi Matt  / @QuantAsylum,

Thanks for addressing these issues. I ran some tests this morning and noticed.
1.  AmpTdhVersusInoutLevel does work up to 96K but you need to enter in 95999.0 This may confuse some users trying to use 96K. (see attached photo) If you run it at 96K it does work for THD but for THD+N it doesn't work unless you use 95999.0 Also when I exported the trace using 96K as a CSV file I got 'Freq, NaN' for the results. I traces exported just fine when I used 95999.0

![20210207_093450](https://user-images.githubusercontent.com/4042250/107133572-567abe80-6935-11eb-8dc8-54d8eb5952b3.jpg)

2.  AmpThdVersusFreq doesn't seam to accept any values above 20K just as it was before. When I did run a plot at up to 20K it seamed to cut off a 6.5K (see attached images)

![20210207_110357](https://user-images.githubusercontent.com/4042250/107133564-524ea100-6935-11eb-9f80-244de0cb51b4.jpg)
![20210207_110531](https://user-images.githubusercontent.com/4042250/107133568-55499180-6935-11eb-9dc4-737272ee42c3.jpg)

Can you please look into this and provide some feedback.
