### ISSUE TITLE
Display options

### ISSUE THREAD

**Issue by stuartmp** [QuantAsylum/QA401#7]
When a settings file is saved the channel that was set is not recorded in the settings file.
I am only testing one channel.
It defaults to left and I have to keep changing the display option to right.
![Screenshot_20200923-134510_Gallery.jpg](https://user-images.githubusercontent.com/4042250/93964481-07c3f200-fda3-11ea-9de0-357165f0167a.jpg)

**Comment by QuantAsylum** [comment]
Thanks! This should be fixed in 1.918
